=== yanaFramework/yanaFramework/trunk/common_files/smilies/config.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT files (file)*>
<!ELEMENT file EMPTY>
<!ATTLIST file
    regex CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== yanaFramework/yanaFramework/trunk/common_files/smilies/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE files SYSTEM "config.dtd">
<files>
    <file name="smile.gif" regex=":[\-oO]?\)|smile"/>
    <file name="boese.gif" regex=":[\-oO]?\(|boese|angry"/>
    <file name="bigsmile.gif" regex="bigsmile"/>
    <file name="chinesisch.gif" regex="chines(isch|e)"/>
    <file name="cool.gif" regex="8[\-oO])"/>
    <file name="engel.gif" regex="engel|angel|good"/>
    <file name="frage.gif" regex="frage|\?"/>
    <file name="grinsen.gif" regex=";[\-oO]\)|grin|grinsen"/>
    <file name="haus.gif" regex="haus|house|home"/>
    <file name="herz.gif" regex="herz|heart"/>
    <file name="hut.gif" regex="h[ua]t"/>
    <file name="idee.gif" regex="ide[ea]"/>
    <file name="ironie.gif" regex="iron(y|ie)"/>
    <file name="keinemeinung.gif" regex=":[\-oO]?\|"/>
    <file name="king.gif" regex="king"/>
    <file name="lachen.gif" regex=":[\-oO]?D|lol|rofl|lachen"/>
    <file name="problem.gif" regex="problem|\?\?"/>
    <file name="schlafen.gif" regex="schlafen|sleep"/>
    <file name="skeptisch.gif" regex="skeptisch|sceptical|skeptical"/>
    <file name="stopp.gif" regex="stopp?"/>
    <file name="teufelchen.gif" regex="&gt;:[\-oO]?\)|teufelchen|devil|evil"/>
    <file name="traurig.gif" regex=":[\'\*]\(|traurig|sad"/>
    <file name="upsidedown.gif" regex="upsidedown|downunder"/>
    <file name="verliebt.gif" regex="verliebt|(in)?love"/>
    <file name="zunge.gif" regex=":[\-oO]?P|zunge|tongue"/>
</files>
