=== yanaFramework/yanaFramework/trunk/config/dtd/skin.dtd
<!ELEMENT skin (head, body)>

<!ELEMENT head (title, author*, url?, description*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
    lang  CDATA  #IMPLIED
>

<!ELEMENT body (template+)>

<!ELEMENT template (language | script | style)*>
<!ATTLIST template
    id    CDATA  #REQUIRED
    file  CDATA  #IMPLIED
>

<!ELEMENT language (#PCDATA)>
<!ATTLIST language
    id  CDATA  #IMPLIED
>

<!ELEMENT script (#PCDATA)>
<!ATTLIST script
    id  CDATA  #IMPLIED
>

<!ELEMENT style (#PCDATA)>
<!ATTLIST style
    id  CDATA  #IMPLIED
>

=== yanaFramework/yanaFramework/trunk/skins/natural.skin.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
  <head>
    <title>Natural Skin</title>

    <author>Thomas Meyer</author>

    <url>http://www.yanaframework.net</url>

    <description>This is a colorful skin that mainly uses brown and yellow,
    which creates some kind of "autumn" mood.</description>

    <description lang="de">Dies ist ein bunter Skin der gelbe und braune
    Farbt√∂ne verwendet. Dies erzeugt eine gewisse
    "Herbststimmung".</description>
  </head>

  <body>
    <template id="INDEX">
      <style id="skin">natural/styles/default_local.css</style>

      <style id="natural">natural/styles/default.css</style>
    </template>

    <template id="GUESTBOOK_ENTRY">
      <style>natural/guestbook/default.css</style>
    </template>

    <template id="GUESTBOOK_READ">
      <style>natural/guestbook/default.css</style>
    </template>

    <template id="GUESTBOOK_DEFAULT_COMMENT">
      <style>natural/guestbook/default.css</style>
    </template>

    <template id="GUESTBOOK_READ_EDIT">
      <style>natural/guestbook/default.css</style>
    </template>
  </body>
</skin>

=== yanaFramework/yanaFramework/trunk/includes/test/resources/skin/default.skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE skin SYSTEM "../../../../config/dtd/skin.dtd">
<skin>
    <head>
        <title>Default</title>
    </head>
    <body>
        <template id="FOO" file="default/default.txt">
            <script>default/default.txt</script>
            <script>default/default.txt</script>
            <style id="test">default/default.txt</style>
            <language>default</language>
        </template>
    </body>
</skin>

=== yanaFramework/yanaFramework/trunk/skins/minimal.skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
    <head>
        <title>Minimal (text only)</title>
        <author>Thomas Meyer</author>
        <url>http://www.yanaframework.net</url>
        <description>
            An elegant, text based skin without unnecessary images.
            The layout is produced by stylesheets.
        </description>
        <description lang="de">
            Ein eleganter, textbasierter Skin ohne überflüssige Grafiken.
            Das Layout wird von Stylesheets geprägt.
        </description>
    </head>
    <body>
        <template id="INDEX" file="minimal/index.html.tpl">
            <style>minimal/styles/menu.css</style>
            <style id="skin">minimal/styles/default.css</style>
        </template>
    </body>
</skin>

=== yanaFramework/yanaFramework/trunk/skins/blue.skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
    <head>
        <title>the BLUE skin</title>
        <author>Thomas Meyer</author>
        <url>http://www.yanaframework.net</url>
        <description>
            A lightweight skin for good performance. Tables without rounded edges.
            The skin uses blue colors (this also makes the name).
        </description>
        <description lang="de">
            Ein schlichter Skin für kurze Ladezeiten. Tabelle ohne runde Kanten.
            Der Skin verwendet primär blaue Farbtöne (daher der Name).
        </description>
    </head>
    <body>
        <template id="INDEX">
        	<style id="blue">blue/styles/default.css</style>
        </template>
    </body>
</skin>

=== yanaFramework/yanaFramework/trunk/skins/summer.skin.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
  <head>
    <title>Summer Skin</title>

    <author>Thomas Meyer</author>

    <url>http://www.yanaframework.net</url>

    <description>This is a skin that uses light blue colors
    creating a "summer" mood.</description>

    <description lang="de">Dies ist ein hellblauer Skin der leichte
    Farbt√∂ne verwendet, um eine "Sommerstimmung" zu erzeugen.</description>
  </head>

  <body>
    <template id="INDEX">
      <style id="skin">summer/styles/default_local.css</style>
      <style id="summer">summer/styles/default.css</style>
    </template>
  </body>
</skin>

=== yanaFramework/yanaFramework/trunk/skins/null.skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
    <head>
        <title>Null (the skin that is no skin)</title>
        <author>Thomas Meyer</author>
        <url>http://www.yanaframework.net</url>
        <description>
            Doesn't have any settings at all.
        </description>
        <description lang="de">
            Hat keine eigenen Layouteinstellungen
        </description>
    </head>
    <body>
        <template id="INDEX" file="null/index.html.tpl"/>
    </body>
</skin>

=== yanaFramework/yanaFramework/trunk/skins/light.skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
    <head>
        <title>Light Skin</title>
        <author>Thomas Meyer</author>
        <url>http://www.yanaframework.net</url>
        <description>
            This skin drops the buttons "New", "Details" and "Overview".
            Instead there is only one view for all.
        </description>
        <description lang="de">
            Dieser Skin verzichtet auf die Schalter "Details", "Einträge" und "Neu".
            Es gibt nur noch eine Ansicht für alles.
        </description>
    </head>
    <body>
        <template id="INDEX" file="light/index.html.tpl">
            <style>light/styles/menu.css</style>
            <style id="skin">light/styles/default.css</style>
        </template>
    </body>
</skin>

=== yanaFramework/yanaFramework/trunk/skins/simple.skin.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE skin SYSTEM "../config/dtd/skin.dtd">
<skin>
    <head>
        <title>Simple Skin</title>
        <author>Thomas Meyer</author>
        <url>http://www.yanaframework.net</url>
        <description>
            A light weight skin for the purists.
            Uses a decent, light gray, with blue highlights.
        </description>
        <description lang="de">
            Ein schlichter Skin f√ºr Puristen.
            Farblich wird ein dezentes Grau verwendet, welches blau abgesetzt ist.
        </description>
    </head>
    <body>
        <template id="INDEX" file="simple/index.html.tpl">
            <style>simple/styles/menu.css</style>
            <style id="skin">simple/styles/default.css</style>
        </template>
    </body>
</skin>
