=== yanaFramework/yanaFramework/trunk/config/dtd/system.config.dtd
<!-- auto-generated DTD -->
<!ELEMENT system (configdir, configdrive, tempdir, plugindir, skindir, blobdir, php_self, authentication+, templates, default, date+)>
<!ELEMENT configdir (#PCDATA)>
<!ELEMENT configdrive (#PCDATA)>
<!ELEMENT tempdir (#PCDATA)>
<!ELEMENT plugindir (#PCDATA)>
<!ELEMENT skindir (#PCDATA)>
<!ELEMENT blobdir (#PCDATA)>
<!ELEMENT php_self (#PCDATA)>
<!ELEMENT authentication (#PCDATA)>
<!ATTLIST authentication
    name CDATA #REQUIRED
  >
<!ELEMENT templates (leftdelimiter, rightdelimiter, templatedir+, cachedir, caching, cachelifetime, cachingtype, compilecheck, compiledir, configdir, debugging, defaultmodifier*, resourcetype*, modifier*, function*, blockfunction*, prefilter*, postfilter*, varfilter*, outputfilter*, defaultresourcetype, usesubdirs, security)*>
<!ELEMENT leftdelimiter (#PCDATA)>
<!ELEMENT rightdelimiter (#PCDATA)>
<!ELEMENT varfilter (#PCDATA)>
<!-- Smarty template left delimiter. -->
<!ELEMENT templatedir (#PCDATA)>
<!ELEMENT cachedir (#PCDATA)>
<!ELEMENT caching (#PCDATA)>
<!ELEMENT cachelifetime (#PCDATA)>
<!ELEMENT cachingtype (#PCDATA)>
<!ELEMENT compilecheck (#PCDATA)>
<!ELEMENT compiledir (#PCDATA)>
<!ELEMENT debugging (#PCDATA)>
<!ELEMENT defaultmodifier (#PCDATA)>
<!ELEMENT resourcetype (#PCDATA)>
<!ATTLIST resourcetype
    name CDATA #IMPLIED
  >
<!ELEMENT modifier (#PCDATA)>
<!ATTLIST modifier
    cacheable CDATA #IMPLIED
    name CDATA #IMPLIED
  >
<!ELEMENT function (#PCDATA)>
<!ATTLIST function
    cacheable CDATA #IMPLIED
    name CDATA #IMPLIED
  >
<!ELEMENT blockfunction (#PCDATA)>
<!ATTLIST blockfunction
    cacheable CDATA #IMPLIED
    name CDATA #IMPLIED
  >
<!ELEMENT prefilter (#PCDATA)>
<!ELEMENT postfilter (#PCDATA)>
<!ELEMENT outputfilter (#PCDATA)>
<!ELEMENT defaultresourcetype (#PCDATA)>
<!ELEMENT usesubdirs (#PCDATA)>
<!ELEMENT security (#PCDATA|library|security|phphandling|securedir|trusteddir|staticclass|phpfunction|phpmodifier|stream|allowedmodifier|disabledmodifier|allowedtag|disabledtag|allowconstants|allowsuperglobals)*>
<!ELEMENT phphandling (#PCDATA)>
<!ELEMENT securedir (#PCDATA)>
<!ELEMENT trusteddir (#PCDATA)>
<!ELEMENT staticclass (#PCDATA)>
<!ELEMENT phpfunction (#PCDATA)>
<!ELEMENT phpmodifier (#PCDATA)>
<!ELEMENT stream (#PCDATA)>
<!ELEMENT allowedmodifier (#PCDATA)>
<!ELEMENT disabledmodifier (#PCDATA)>
<!ELEMENT allowedtag (#PCDATA)>
<!ELEMENT disabledtag (#PCDATA)>
<!ELEMENT allowconstants (#PCDATA)>
<!ELEMENT allowsuperglobals (#PCDATA)>
<!ELEMENT default (#PCDATA|profile|homepage|message|event|skin|language|database|user|user_requirements|multicast_groups|security|library|default|update_server)*>
<!ELEMENT profile (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT event (template|safemode|type)*>
<!ELEMENT type (#PCDATA)>
<!ELEMENT safemode (#PCDATA)>
<!ELEMENT template (#PCDATA)>
<!ELEMENT skin (directory)*>
<!ELEMENT directory (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT database (require_odbc|options)*>
<!ELEMENT options (ssl|persistent)*>
<!ELEMENT persistent (#PCDATA)>
<!ELEMENT ssl (#PCDATA)>
<!ELEMENT require_odbc (#PCDATA)>
<!ELEMENT user (user_active|level|role|group)*>
<!ELEMENT user_requirements (level|role|group)*>
<!ELEMENT group (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT user_active (#PCDATA)>
<!ELEMENT multicast_groups (default|primary|config|security|write|read)*>
<!ELEMENT read (#PCDATA|default|primary|read|library|security)*>
<!ELEMENT library (#PCDATA)>
<!ELEMENT primary (#PCDATA|primary|library|security)*>
<!ELEMENT write (#PCDATA|default|primary|write|library|security)*>
<!ELEMENT config (#PCDATA|config|library|security)*>
<!ELEMENT update_server (#PCDATA)>
<!ELEMENT date (php|js)*>
<!ELEMENT js (#PCDATA)>
<!ELEMENT php (#PCDATA)>

=== yanaFramework/yanaFramework/trunk/config/system.config.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE system SYSTEM "dtd/system.config.dtd">
<system>
    <!--
        Diese Datei enth채lt Pfadangaben zu Konfigurationsdateien!
        Die enthaltenen Eintr채ge d체rfen auf keinen Fall ge채ndert werden.
        
        This file contains information about paths to configuration files!
        The contained entries may not be changed at any case.
    -->
    <configdir>config/</configdir>
    <configdrive>config/system.drive.xml</configdrive>
    <tempdir>cache/</tempdir>
    <plugincache>cache/pluginmanager.tmp</plugincache>
    <plugindir>plugins/</plugindir>
    <pluginfile>config/plugins.cfg</pluginfile>
    <php_self>index.php</php_self>
    <default>
    	<profile>default</profile>
    	<homepage>sitemap</homepage>
    	<message>false</message>
    	<event>
    		<type>default</type>
    		<safemode>0</safemode>
    		<template>index</template>
    	</event>
    	<skin>
    		<directory>default/</directory>
    	</skin>
    	<language>de</language>
    	<database>
    		<options>
    			<autofree>true</autofree>
    			<persistent>true</persistent>
    			<ssl>false</ssl>
    		</options>
    		<require_odbc>db2</require_odbc>
    		<require_odbc>access</require_odbc>
    	</database>
    	<user>
    		<group>REGISTERED</group>
    		<role>DEFAULT</role>
    		<level>0</level>
    		<user_active>true</user_active>
    	</user>
    	<multicast_groups>
    		<read>
    			<security>true</security>
    			<library>true</library>
    			<read>true</read>
    			<primary>true</primary>
    			<default>true</default>
            </read>
    		<write>
    			<security>true</security>
    			<library>true</library>
    			<write>true</write>
    			<primary>true</primary>
    			<default>true</default>
            </write>
    		<security>
    			<security>true</security>
    			<library>true</library>
            </security>
    		<config>
    			<security>true</security>
    			<library>true</library>
    			<config>true</config>
            </config>
    		<primary>
    			<security>true</security>
    			<library>true</library>
    			<primary>true</primary>
            </primary>
    		<default>
    			<security>true</security>
    			<library>true</library>
    			<default>true</default>
            </default>
    	</multicast_groups>
    	<update_server>http://yanaframework.net/pages/update.php?version={$VERSION}&#38;amp;stable={$IS_STABLE}&#38;amp;lang={$LANG}&#38;amp;asnumber={$AS_NUMBER}</update_server>
    </default>
    <date>
		<js>date.getDate() +'-'+ (date.getMonth()+1) +'-'+ date.getFullYear()</js>
		<php>j-n-Y</php>
    </date>
    <date>
		<js>date.toLocaleTimeString()</js>
		<php>G:i:s</php>
    </date>
    <date>
		<js>date.getDate() +'-'+ (date.getMonth()+1) +'-'+ date.getFullYear() +' '+ date.toLocaleTimeString()</js>
		<php>j-n-Y G:i:s</php>
    </date>
    <date>
		<js>date.getDate() +'-'+ (date.getMonth()+1) +'-'+ date.getFullYear() +' '+ date.toTimeString()</js>
		<php>j-n-Y G:i:s O</php>
    </date>
    <date>
		<js>date.toLocaleDateString()</js>
		<php>l, j F Y</php>
    </date>
    <date>
		<js>date.toLocaleString()</js>
		<php>r</php>
    </date>
</system>
